modLoader="javafml"
loaderVersion="47,)"
license="All Rights Reserved, DragN0007"
#issueTrackerURL="https://discord.gg/2WznNTtVac"
[[mods]]
modId="vherbalism"
version="${1.3}"
displayName="SL-Herbalism"
logoFile="herbalism_logo.png"
authors="DragN0007, Astralsleeperr, ✧ index"
description='''
Adds herbs for cats! Part of Second Light SMP.
'''
[[dependencies.vherbalism]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.vherbalism]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.vherbalism]]
modId = "thirst"
mandatory = true
versionRange = "[1.3.8,]"
ordering = "NONE"
side = "BOTH"
[[mixins]]
config = "vherbalism.mixins.json"
