modLoader="javafml"
loaderVersion="47,)"
license="All Rights Reserved, DragN0007"
#issueTrackerURL="https://discord.gg/2WznNTtVac"
[[mods]]
modId="vherbalism"
version="${1.0}"
displayName="V-Herbalism"
logoFile="herbalism_logo.png"
authors="DragN0007"
description='''
Adds herbs for cats!
'''
[[dependencies.vherbalism]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.vherbalism]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.vherbalism]]
modId = "thirst"
mandatory = true
versionRange = "[1.3.8,]"
ordering = "NONE"
side = "BOTH"